[workspace]
members = [
    "compiler/blastf_ast",
    "compiler/blastf_name"
]

[package]
name = "blastfurnace-workspaces"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
